-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 09:44:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pedido_2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pedido_2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pedido_2019` DEFAULT CHARACTER SET utf8 ;
USE `Pedido_2019` ;

-- -----------------------------------------------------
-- Table `Pedido_2019`.`valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`valor` (
  `idvalor` INT NOT NULL AUTO_INCREMENT,
  `valorlista` VARCHAR(45) NOT NULL,
  `valordistribuidor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvalor`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Pedido_2019`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`producto` (
  `idproducto` INT NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `idvalor` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `idvalor_idx` (`idvalor` ASC),
  CONSTRAINT `idvalor`
    FOREIGN KEY (`idvalor`)
    REFERENCES `Pedido_2019`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`region` (
  `idregion` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`comuna` (
  `idcomuna` INT NOT NULL AUTO_INCREMENT,
  `comuna` VARCHAR(45) NOT NULL,
  `idregion` INT NOT NULL,
  PRIMARY KEY (`idcomuna`),
  INDEX `idregion_idx` (`idregion` ASC),
  CONSTRAINT `idregion`
    FOREIGN KEY (`idregion`)
    REFERENCES `Pedido_2019`.`region` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `Pedido_2019`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `clave` BLOB NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idrol_idx` (`idrol` ASC),
  CONSTRAINT `idrol`
    FOREIGN KEY (`idrol`)
    REFERENCES `Pedido_2019`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`direccion` (
  `iddireccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  `idcomuna` INT NOT NULL,
  PRIMARY KEY (`iddireccion`),
  INDEX `idcomuna_idx` (`idcomuna` ASC),
  INDEX `idusuario_idx` (`idusuario` ASC),
  CONSTRAINT `idcomuna`
    FOREIGN KEY (`idcomuna`)
    REFERENCES `Pedido_2019`.`comuna` (`idcomuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `Pedido_2019`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`estado` (
  `idestado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`cliente` (
  `idrut` INT NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `iddireccion` INT NOT NULL,
  `idcredito` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idrut`),
  INDEX `iddireccion_idx` (`iddireccion` ASC),
  INDEX `idcategoria_idx` (`idcategoria` ASC),
  INDEX `idestado_idx` (`idestado` ASC),
  CONSTRAINT `iddireccion`
    FOREIGN KEY (`iddireccion`)
    REFERENCES `Pedido_2019`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `Pedido_2019`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idestado`
    FOREIGN KEY (`idestado`)
    REFERENCES `Pedido_2019`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` VARCHAR(45) NOT NULL,
  `fecha_salida` VARCHAR(45) NOT NULL,
  `monto` INT NOT NULL,
  `idrut` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `idrut_idx` (`idrut` ASC),
  CONSTRAINT `idrut`
    FOREIGN KEY (`idrut`)
    REFERENCES `Pedido_2019`.`cliente` (`idrut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_2019`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_2019`.`detallepedido` (
  `iddetallepedido` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idpedido` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`iddetallepedido`),
  INDEX `idproducto_idx` (`idproducto` ASC),
  INDEX `idpedido_idx` (`idpedido` ASC),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `Pedido_2019`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `Pedido_2019`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
