-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 02:08:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pedido_2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pedido_2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedido_2019` DEFAULT CHARACTER SET utf8 ;
USE `pedido_2019` ;

-- -----------------------------------------------------
-- Table `pedido_2019`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`condicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`condicion` (
  `idcondicion` INT(11) NOT NULL AUTO_INCREMENT,
  `condicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcondicion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`estado` (
  `idestado` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`cliente` (
  `idrut` INT(11) NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `idcondicion` INT(11) NOT NULL,
  `idcategoria` INT(11) NOT NULL,
  `idestado` INT(11) NOT NULL,
  PRIMARY KEY (`idrut`),
  INDEX `idcategoria_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `idcondicion_idx` (`idcondicion` ASC) VISIBLE,
  INDEX `idestado_idx` (`idestado` ASC) VISIBLE,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `pedido_2019`.`categoria` (`idcategoria`),
  CONSTRAINT `idcondicion`
    FOREIGN KEY (`idcondicion`)
    REFERENCES `pedido_2019`.`condicion` (`idcondicion`),
  CONSTRAINT `idestado`
    FOREIGN KEY (`idestado`)
    REFERENCES `pedido_2019`.`estado` (`idestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`region` (
  `idregion` INT(11) NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`comuna` (
  `idcomuna` INT(11) NOT NULL AUTO_INCREMENT,
  `comuna` VARCHAR(45) NOT NULL,
  `idregion` INT(11) NOT NULL,
  PRIMARY KEY (`idcomuna`),
  INDEX `idregion_idx` (`idregion` ASC) VISIBLE,
  CONSTRAINT `idregion`
    FOREIGN KEY (`idregion`)
    REFERENCES `pedido_2019`.`region` (`idregion`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `pedido_2019`.`estadopedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`estadopedido` (
  `idestadopedido` INT(11) NOT NULL AUTO_INCREMENT,
  `estadopedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestadopedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `clave` BLOB NOT NULL,
  `idrol` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idrol_idx` (`idrol` ASC) VISIBLE,
  CONSTRAINT `idrol`
    FOREIGN KEY (`idrol`)
    REFERENCES `pedido_2019`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`direccion` (
  `iddireccion` INT(11) NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  `idcomuna` INT(11) NOT NULL,
  `idrut` INT NOT NULL,
  PRIMARY KEY (`iddireccion`),
  INDEX `idcomuna_idx` (`idcomuna` ASC) VISIBLE,
  INDEX `idusuario_idx` (`idusuario` ASC) VISIBLE,
  INDEX `idrut_idx` (`idrut` ASC) VISIBLE,
  CONSTRAINT `idcomuna`
    FOREIGN KEY (`idcomuna`)
    REFERENCES `pedido_2019`.`comuna` (`idcomuna`),
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `pedido_2019`.`usuario` (`idusuario`),
  CONSTRAINT `idrut`
    FOREIGN KEY (`idrut`)
    REFERENCES `pedido_2019`.`cliente` (`idrut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` VARCHAR(45) NOT NULL,
  `fecha_salida` VARCHAR(45) NOT NULL,
  `monto` INT(11) NOT NULL,
  `idestadopedido` INT(11) NOT NULL,
  `iddireccion` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `idestadopedido_idx` (`idestadopedido` ASC) VISIBLE,
  INDEX `iddireccion_idx` (`iddireccion` ASC) VISIBLE,
  CONSTRAINT `idestadopedido`
    FOREIGN KEY (`idestadopedido`)
    REFERENCES `pedido_2019`.`estadopedido` (`idestadopedido`),
  CONSTRAINT `iddireccion`
    FOREIGN KEY (`iddireccion`)
    REFERENCES `pedido_2019`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`producto` (
  `idproducto` INT(11) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `valorlista` INT(11) NOT NULL,
  `valordescuento` VARCHAR(45) NOT NULL,
  `valordescuentoespecial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido_2019`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido_2019`.`detallepedido` (
  `iddetallepedido` INT(11) NOT NULL AUTO_INCREMENT,
  `idproducto` INT(11) NOT NULL,
  `idpedido` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`iddetallepedido`),
  INDEX `idproducto_idx` (`idproducto` ASC) VISIBLE,
  INDEX `idpedido_idx` (`idpedido` ASC) VISIBLE,
  CONSTRAINT `idpedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pedido_2019`.`pedido` (`idpedido`),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `pedido_2019`.`producto` (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
